name: Order Coffee

on:
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Install Apidog CLI
        run: npm install -g apidog-cli

      - name: Running Test Scenario
        run: apidog run --access-token ${{ secrets.APIDOG_ACCESS_TOKEN }} -t 784783 -e 2355339 -n 1 --delay-request 5000 -r html,json --out-dir reports/$(date +%Y-%m-%d_%H:%M:%S) --out-file index

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Commit and Push Reports
        run: |
          git add reports/
          git commit -m "Add API test reports from automated run of Stop Tests" || echo "No changes to commit"
          git push origin HEAD:gh-pages

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: reports

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
