name: Order Coffee

on:
  workflow_dispatch:

jobs:
  request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Run the curl command and save the response
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H:%M:%S")
          curl -X POST "https://teacoffee.dreamsinternational.in/order" \
          -H "Content-Type: application/json" \
          -d '{"name": "Sayantan", "item": "coffee", "quantity": "1"}' \
          -D coffee/${TIMESTAMP}_header.http \
          -o coffee/${TIMESTAMP}_body.json

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Commit and Push Reports
        run: |
          git add coffee/
          git commit -m "Add coffee API results from automated run of Order Coffee" || echo "No changes to commit"
          git push origin HEAD:gh-pages

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: coffee

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: coffee/

  deploy:
    needs: request
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
