name: Start API Test

on:
  schedule:
    - cron: "30 10 * * 1-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install Apidog CLI
        run: npm install -g apidog-cli

      - name: Running Test Scenario
        run: apidog run --access-token ${{ secrets.APIDOG_ACCESS_TOKEN }} -t 784776 -e 2355339 -n 1 --delay-request 5000 -r html,cli --output-dir reports/${{ env.timestamp }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
      - name: Commit and Push Reports
        run: |
          git add reports/
          git commit -m "Add API test reports from automated run on ${{ env.timestamp }}" || echo "No changes to commit"
          git push origin HEAD:main
